# Environment variables
# env = XCURSOR_SIZE,24
env = TERMINAL,foot
env = QSG_RENDER_LOOP=threaded

# Startup applications
exec-once = brave

exec-once = [workspace 6 silent] discord
exec-once = [workspace 6 silent] slack
exec-once = [workspace 6 silent] Telegram

exec-once = emacs --daemon
# exec-once = flameshot
exec-once = copyq
exec-once = QT_SCALE_FACTOR=1.15 qs
exec-once = hyprpaper
